// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerLogin.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PlayerLogin_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PlayerLogin_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PlayerLogin_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PlayerLogin_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PlayerLogin_2eproto;
class BenchTest;
class BenchTestDefaultTypeInternal;
extern BenchTestDefaultTypeInternal _BenchTest_default_instance_;
class LogicEnterFromAccountServer;
class LogicEnterFromAccountServerDefaultTypeInternal;
extern LogicEnterFromAccountServerDefaultTypeInternal _LogicEnterFromAccountServer_default_instance_;
class PlayerEnter;
class PlayerEnterDefaultTypeInternal;
extern PlayerEnterDefaultTypeInternal _PlayerEnter_default_instance_;
class PlayerEnterAck;
class PlayerEnterAckDefaultTypeInternal;
extern PlayerEnterAckDefaultTypeInternal _PlayerEnterAck_default_instance_;
class PlayerLogin;
class PlayerLoginDefaultTypeInternal;
extern PlayerLoginDefaultTypeInternal _PlayerLogin_default_instance_;
class PlayerLoginAck;
class PlayerLoginAckDefaultTypeInternal;
extern PlayerLoginAckDefaultTypeInternal _PlayerLoginAck_default_instance_;
class PlayerRegsiter;
class PlayerRegsiterDefaultTypeInternal;
extern PlayerRegsiterDefaultTypeInternal _PlayerRegsiter_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::BenchTest* Arena::CreateMaybeMessage<::BenchTest>(Arena*);
template<> ::LogicEnterFromAccountServer* Arena::CreateMaybeMessage<::LogicEnterFromAccountServer>(Arena*);
template<> ::PlayerEnter* Arena::CreateMaybeMessage<::PlayerEnter>(Arena*);
template<> ::PlayerEnterAck* Arena::CreateMaybeMessage<::PlayerEnterAck>(Arena*);
template<> ::PlayerLogin* Arena::CreateMaybeMessage<::PlayerLogin>(Arena*);
template<> ::PlayerLoginAck* Arena::CreateMaybeMessage<::PlayerLoginAck>(Arena*);
template<> ::PlayerRegsiter* Arena::CreateMaybeMessage<::PlayerRegsiter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum PlayerLoginAck_CheckResult : int {
  PlayerLoginAck_CheckResult_Pass = 0,
  PlayerLoginAck_CheckResult_Refuse = 1,
  PlayerLoginAck_CheckResult_PlayerLoginAck_CheckResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PlayerLoginAck_CheckResult_PlayerLoginAck_CheckResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PlayerLoginAck_CheckResult_IsValid(int value);
constexpr PlayerLoginAck_CheckResult PlayerLoginAck_CheckResult_CheckResult_MIN = PlayerLoginAck_CheckResult_Pass;
constexpr PlayerLoginAck_CheckResult PlayerLoginAck_CheckResult_CheckResult_MAX = PlayerLoginAck_CheckResult_Refuse;
constexpr int PlayerLoginAck_CheckResult_CheckResult_ARRAYSIZE = PlayerLoginAck_CheckResult_CheckResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerLoginAck_CheckResult_descriptor();
template<typename T>
inline const std::string& PlayerLoginAck_CheckResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerLoginAck_CheckResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerLoginAck_CheckResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerLoginAck_CheckResult_descriptor(), enum_t_value);
}
inline bool PlayerLoginAck_CheckResult_Parse(
    const std::string& name, PlayerLoginAck_CheckResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerLoginAck_CheckResult>(
    PlayerLoginAck_CheckResult_descriptor(), name, value);
}
// ===================================================================

class PlayerLogin :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerLogin) */ {
 public:
  PlayerLogin();
  virtual ~PlayerLogin();

  PlayerLogin(const PlayerLogin& from);
  PlayerLogin(PlayerLogin&& from) noexcept
    : PlayerLogin() {
    *this = ::std::move(from);
  }

  inline PlayerLogin& operator=(const PlayerLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerLogin& operator=(PlayerLogin&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerLogin& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerLogin* internal_default_instance() {
    return reinterpret_cast<const PlayerLogin*>(
               &_PlayerLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerLogin& a, PlayerLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerLogin* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerLogin* New() const final {
    return CreateMaybeMessage<PlayerLogin>(nullptr);
  }

  PlayerLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerLogin>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerLogin& from);
  void MergeFrom(const PlayerLogin& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerLogin* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerLogin";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // bytes account = 1;
  void clear_account();
  const std::string& account() const;
  void set_account(const std::string& value);
  void set_account(std::string&& value);
  void set_account(const char* value);
  void set_account(const void* value, size_t size);
  std::string* mutable_account();
  std::string* release_account();
  void set_allocated_account(std::string* account);

  // bytes password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const void* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);

  // @@protoc_insertion_point(class_scope:PlayerLogin)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class PlayerRegsiter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerRegsiter) */ {
 public:
  PlayerRegsiter();
  virtual ~PlayerRegsiter();

  PlayerRegsiter(const PlayerRegsiter& from);
  PlayerRegsiter(PlayerRegsiter&& from) noexcept
    : PlayerRegsiter() {
    *this = ::std::move(from);
  }

  inline PlayerRegsiter& operator=(const PlayerRegsiter& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerRegsiter& operator=(PlayerRegsiter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerRegsiter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerRegsiter* internal_default_instance() {
    return reinterpret_cast<const PlayerRegsiter*>(
               &_PlayerRegsiter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerRegsiter& a, PlayerRegsiter& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerRegsiter* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerRegsiter* New() const final {
    return CreateMaybeMessage<PlayerRegsiter>(nullptr);
  }

  PlayerRegsiter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerRegsiter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerRegsiter& from);
  void MergeFrom(const PlayerRegsiter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerRegsiter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerRegsiter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // bytes account = 1;
  void clear_account();
  const std::string& account() const;
  void set_account(const std::string& value);
  void set_account(std::string&& value);
  void set_account(const char* value);
  void set_account(const void* value, size_t size);
  std::string* mutable_account();
  std::string* release_account();
  void set_allocated_account(std::string* account);

  // bytes password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const void* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);

  // @@protoc_insertion_point(class_scope:PlayerRegsiter)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class PlayerLoginAck :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerLoginAck) */ {
 public:
  PlayerLoginAck();
  virtual ~PlayerLoginAck();

  PlayerLoginAck(const PlayerLoginAck& from);
  PlayerLoginAck(PlayerLoginAck&& from) noexcept
    : PlayerLoginAck() {
    *this = ::std::move(from);
  }

  inline PlayerLoginAck& operator=(const PlayerLoginAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerLoginAck& operator=(PlayerLoginAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerLoginAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerLoginAck* internal_default_instance() {
    return reinterpret_cast<const PlayerLoginAck*>(
               &_PlayerLoginAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerLoginAck& a, PlayerLoginAck& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerLoginAck* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerLoginAck* New() const final {
    return CreateMaybeMessage<PlayerLoginAck>(nullptr);
  }

  PlayerLoginAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerLoginAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerLoginAck& from);
  void MergeFrom(const PlayerLoginAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerLoginAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerLoginAck";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef PlayerLoginAck_CheckResult CheckResult;
  static constexpr CheckResult Pass =
    PlayerLoginAck_CheckResult_Pass;
  static constexpr CheckResult Refuse =
    PlayerLoginAck_CheckResult_Refuse;
  static inline bool CheckResult_IsValid(int value) {
    return PlayerLoginAck_CheckResult_IsValid(value);
  }
  static constexpr CheckResult CheckResult_MIN =
    PlayerLoginAck_CheckResult_CheckResult_MIN;
  static constexpr CheckResult CheckResult_MAX =
    PlayerLoginAck_CheckResult_CheckResult_MAX;
  static constexpr int CheckResult_ARRAYSIZE =
    PlayerLoginAck_CheckResult_CheckResult_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  CheckResult_descriptor() {
    return PlayerLoginAck_CheckResult_descriptor();
  }
  template<typename T>
  static inline const std::string& CheckResult_Name(T enum_t_value) {
    static_assert(::std::is_same<T, CheckResult>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function CheckResult_Name.");
    return PlayerLoginAck_CheckResult_Name(enum_t_value);
  }
  static inline bool CheckResult_Parse(const std::string& name,
      CheckResult* value) {
    return PlayerLoginAck_CheckResult_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSessionKeyFieldNumber = 1,
    kResultFieldNumber = 2,
  };
  // uint32 session_key = 1;
  void clear_session_key();
  ::PROTOBUF_NAMESPACE_ID::uint32 session_key() const;
  void set_session_key(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // .PlayerLoginAck.CheckResult result = 2;
  void clear_result();
  ::PlayerLoginAck_CheckResult result() const;
  void set_result(::PlayerLoginAck_CheckResult value);

  // @@protoc_insertion_point(class_scope:PlayerLoginAck)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 session_key_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class LogicEnterFromAccountServer :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LogicEnterFromAccountServer) */ {
 public:
  LogicEnterFromAccountServer();
  virtual ~LogicEnterFromAccountServer();

  LogicEnterFromAccountServer(const LogicEnterFromAccountServer& from);
  LogicEnterFromAccountServer(LogicEnterFromAccountServer&& from) noexcept
    : LogicEnterFromAccountServer() {
    *this = ::std::move(from);
  }

  inline LogicEnterFromAccountServer& operator=(const LogicEnterFromAccountServer& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogicEnterFromAccountServer& operator=(LogicEnterFromAccountServer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogicEnterFromAccountServer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogicEnterFromAccountServer* internal_default_instance() {
    return reinterpret_cast<const LogicEnterFromAccountServer*>(
               &_LogicEnterFromAccountServer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LogicEnterFromAccountServer& a, LogicEnterFromAccountServer& b) {
    a.Swap(&b);
  }
  inline void Swap(LogicEnterFromAccountServer* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogicEnterFromAccountServer* New() const final {
    return CreateMaybeMessage<LogicEnterFromAccountServer>(nullptr);
  }

  LogicEnterFromAccountServer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogicEnterFromAccountServer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogicEnterFromAccountServer& from);
  void MergeFrom(const LogicEnterFromAccountServer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogicEnterFromAccountServer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LogicEnterFromAccountServer";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountKeyFieldNumber = 2,
    kSessionKeyFieldNumber = 1,
  };
  // uint64 account_key = 2;
  void clear_account_key();
  ::PROTOBUF_NAMESPACE_ID::uint64 account_key() const;
  void set_account_key(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint32 session_key = 1;
  void clear_session_key();
  ::PROTOBUF_NAMESPACE_ID::uint32 session_key() const;
  void set_session_key(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:LogicEnterFromAccountServer)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 account_key_;
  ::PROTOBUF_NAMESPACE_ID::uint32 session_key_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class PlayerEnter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerEnter) */ {
 public:
  PlayerEnter();
  virtual ~PlayerEnter();

  PlayerEnter(const PlayerEnter& from);
  PlayerEnter(PlayerEnter&& from) noexcept
    : PlayerEnter() {
    *this = ::std::move(from);
  }

  inline PlayerEnter& operator=(const PlayerEnter& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerEnter& operator=(PlayerEnter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerEnter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerEnter* internal_default_instance() {
    return reinterpret_cast<const PlayerEnter*>(
               &_PlayerEnter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PlayerEnter& a, PlayerEnter& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerEnter* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerEnter* New() const final {
    return CreateMaybeMessage<PlayerEnter>(nullptr);
  }

  PlayerEnter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerEnter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerEnter& from);
  void MergeFrom(const PlayerEnter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerEnter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerEnter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PlayerEnter)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class PlayerEnterAck :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerEnterAck) */ {
 public:
  PlayerEnterAck();
  virtual ~PlayerEnterAck();

  PlayerEnterAck(const PlayerEnterAck& from);
  PlayerEnterAck(PlayerEnterAck&& from) noexcept
    : PlayerEnterAck() {
    *this = ::std::move(from);
  }

  inline PlayerEnterAck& operator=(const PlayerEnterAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerEnterAck& operator=(PlayerEnterAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerEnterAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerEnterAck* internal_default_instance() {
    return reinterpret_cast<const PlayerEnterAck*>(
               &_PlayerEnterAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PlayerEnterAck& a, PlayerEnterAck& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerEnterAck* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerEnterAck* New() const final {
    return CreateMaybeMessage<PlayerEnterAck>(nullptr);
  }

  PlayerEnterAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerEnterAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerEnterAck& from);
  void MergeFrom(const PlayerEnterAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerEnterAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerEnterAck";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PlayerEnterAck)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// -------------------------------------------------------------------

class BenchTest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BenchTest) */ {
 public:
  BenchTest();
  virtual ~BenchTest();

  BenchTest(const BenchTest& from);
  BenchTest(BenchTest&& from) noexcept
    : BenchTest() {
    *this = ::std::move(from);
  }

  inline BenchTest& operator=(const BenchTest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BenchTest& operator=(BenchTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BenchTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BenchTest* internal_default_instance() {
    return reinterpret_cast<const BenchTest*>(
               &_BenchTest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(BenchTest& a, BenchTest& b) {
    a.Swap(&b);
  }
  inline void Swap(BenchTest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BenchTest* New() const final {
    return CreateMaybeMessage<BenchTest>(nullptr);
  }

  BenchTest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BenchTest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BenchTest& from);
  void MergeFrom(const BenchTest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BenchTest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BenchTest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerLogin_2eproto);
    return ::descriptor_table_PlayerLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumFieldNumber = 1,
  };
  // uint32 num = 1;
  void clear_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 num() const;
  void set_num(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:BenchTest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerLogin_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerLogin

// bytes account = 1;
inline void PlayerLogin::clear_account() {
  account_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PlayerLogin::account() const {
  // @@protoc_insertion_point(field_get:PlayerLogin.account)
  return account_.GetNoArena();
}
inline void PlayerLogin::set_account(const std::string& value) {
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlayerLogin.account)
}
inline void PlayerLogin::set_account(std::string&& value) {
  
  account_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlayerLogin.account)
}
inline void PlayerLogin::set_account(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlayerLogin.account)
}
inline void PlayerLogin::set_account(const void* value, size_t size) {
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlayerLogin.account)
}
inline std::string* PlayerLogin::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:PlayerLogin.account)
  return account_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PlayerLogin::release_account() {
  // @@protoc_insertion_point(field_release:PlayerLogin.account)
  
  return account_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerLogin::set_allocated_account(std::string* account) {
  if (account != nullptr) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:PlayerLogin.account)
}

// bytes password = 2;
inline void PlayerLogin::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PlayerLogin::password() const {
  // @@protoc_insertion_point(field_get:PlayerLogin.password)
  return password_.GetNoArena();
}
inline void PlayerLogin::set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlayerLogin.password)
}
inline void PlayerLogin::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlayerLogin.password)
}
inline void PlayerLogin::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlayerLogin.password)
}
inline void PlayerLogin::set_password(const void* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlayerLogin.password)
}
inline std::string* PlayerLogin::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:PlayerLogin.password)
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PlayerLogin::release_password() {
  // @@protoc_insertion_point(field_release:PlayerLogin.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerLogin::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:PlayerLogin.password)
}

// -------------------------------------------------------------------

// PlayerRegsiter

// bytes account = 1;
inline void PlayerRegsiter::clear_account() {
  account_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PlayerRegsiter::account() const {
  // @@protoc_insertion_point(field_get:PlayerRegsiter.account)
  return account_.GetNoArena();
}
inline void PlayerRegsiter::set_account(const std::string& value) {
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlayerRegsiter.account)
}
inline void PlayerRegsiter::set_account(std::string&& value) {
  
  account_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlayerRegsiter.account)
}
inline void PlayerRegsiter::set_account(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlayerRegsiter.account)
}
inline void PlayerRegsiter::set_account(const void* value, size_t size) {
  
  account_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlayerRegsiter.account)
}
inline std::string* PlayerRegsiter::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:PlayerRegsiter.account)
  return account_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PlayerRegsiter::release_account() {
  // @@protoc_insertion_point(field_release:PlayerRegsiter.account)
  
  return account_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerRegsiter::set_allocated_account(std::string* account) {
  if (account != nullptr) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:PlayerRegsiter.account)
}

// bytes password = 2;
inline void PlayerRegsiter::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PlayerRegsiter::password() const {
  // @@protoc_insertion_point(field_get:PlayerRegsiter.password)
  return password_.GetNoArena();
}
inline void PlayerRegsiter::set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PlayerRegsiter.password)
}
inline void PlayerRegsiter::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PlayerRegsiter.password)
}
inline void PlayerRegsiter::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PlayerRegsiter.password)
}
inline void PlayerRegsiter::set_password(const void* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PlayerRegsiter.password)
}
inline std::string* PlayerRegsiter::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:PlayerRegsiter.password)
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PlayerRegsiter::release_password() {
  // @@protoc_insertion_point(field_release:PlayerRegsiter.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerRegsiter::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:PlayerRegsiter.password)
}

// -------------------------------------------------------------------

// PlayerLoginAck

// uint32 session_key = 1;
inline void PlayerLoginAck::clear_session_key() {
  session_key_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PlayerLoginAck::session_key() const {
  // @@protoc_insertion_point(field_get:PlayerLoginAck.session_key)
  return session_key_;
}
inline void PlayerLoginAck::set_session_key(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  session_key_ = value;
  // @@protoc_insertion_point(field_set:PlayerLoginAck.session_key)
}

// .PlayerLoginAck.CheckResult result = 2;
inline void PlayerLoginAck::clear_result() {
  result_ = 0;
}
inline ::PlayerLoginAck_CheckResult PlayerLoginAck::result() const {
  // @@protoc_insertion_point(field_get:PlayerLoginAck.result)
  return static_cast< ::PlayerLoginAck_CheckResult >(result_);
}
inline void PlayerLoginAck::set_result(::PlayerLoginAck_CheckResult value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:PlayerLoginAck.result)
}

// -------------------------------------------------------------------

// LogicEnterFromAccountServer

// uint32 session_key = 1;
inline void LogicEnterFromAccountServer::clear_session_key() {
  session_key_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LogicEnterFromAccountServer::session_key() const {
  // @@protoc_insertion_point(field_get:LogicEnterFromAccountServer.session_key)
  return session_key_;
}
inline void LogicEnterFromAccountServer::set_session_key(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  session_key_ = value;
  // @@protoc_insertion_point(field_set:LogicEnterFromAccountServer.session_key)
}

// uint64 account_key = 2;
inline void LogicEnterFromAccountServer::clear_account_key() {
  account_key_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LogicEnterFromAccountServer::account_key() const {
  // @@protoc_insertion_point(field_get:LogicEnterFromAccountServer.account_key)
  return account_key_;
}
inline void LogicEnterFromAccountServer::set_account_key(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  account_key_ = value;
  // @@protoc_insertion_point(field_set:LogicEnterFromAccountServer.account_key)
}

// -------------------------------------------------------------------

// PlayerEnter

// -------------------------------------------------------------------

// PlayerEnterAck

// -------------------------------------------------------------------

// BenchTest

// uint32 num = 1;
inline void BenchTest::clear_num() {
  num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 BenchTest::num() const {
  // @@protoc_insertion_point(field_get:BenchTest.num)
  return num_;
}
inline void BenchTest::set_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:BenchTest.num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PlayerLoginAck_CheckResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PlayerLoginAck_CheckResult>() {
  return ::PlayerLoginAck_CheckResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PlayerLogin_2eproto
