// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerLink.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ServerLink_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ServerLink_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ServerLink_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ServerLink_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ServerLink_2eproto;
class DataBaseNotify;
class DataBaseNotifyDefaultTypeInternal;
extern DataBaseNotifyDefaultTypeInternal _DataBaseNotify_default_instance_;
class ServerLink;
class ServerLinkDefaultTypeInternal;
extern ServerLinkDefaultTypeInternal _ServerLink_default_instance_;
class ServerMessageRegister;
class ServerMessageRegisterDefaultTypeInternal;
extern ServerMessageRegisterDefaultTypeInternal _ServerMessageRegister_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DataBaseNotify* Arena::CreateMaybeMessage<::DataBaseNotify>(Arena*);
template<> ::ServerLink* Arena::CreateMaybeMessage<::ServerLink>(Arena*);
template<> ::ServerMessageRegister* Arena::CreateMaybeMessage<::ServerMessageRegister>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ServerLink :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerLink) */ {
 public:
  ServerLink();
  virtual ~ServerLink();

  ServerLink(const ServerLink& from);
  ServerLink(ServerLink&& from) noexcept
    : ServerLink() {
    *this = ::std::move(from);
  }

  inline ServerLink& operator=(const ServerLink& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerLink& operator=(ServerLink&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerLink& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerLink* internal_default_instance() {
    return reinterpret_cast<const ServerLink*>(
               &_ServerLink_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerLink& a, ServerLink& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerLink* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerLink* New() const final {
    return CreateMaybeMessage<ServerLink>(nullptr);
  }

  ServerLink* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerLink>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerLink& from);
  void MergeFrom(const ServerLink& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerLink* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerLink";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ServerLink_2eproto);
    return ::descriptor_table_ServerLink_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerStrFieldNumber = 1,
  };
  // string server_str = 1;
  void clear_server_str();
  const std::string& server_str() const;
  void set_server_str(const std::string& value);
  void set_server_str(std::string&& value);
  void set_server_str(const char* value);
  void set_server_str(const char* value, size_t size);
  std::string* mutable_server_str();
  std::string* release_server_str();
  void set_allocated_server_str(std::string* server_str);

  // @@protoc_insertion_point(class_scope:ServerLink)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_str_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ServerLink_2eproto;
};
// -------------------------------------------------------------------

class DataBaseNotify :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DataBaseNotify) */ {
 public:
  DataBaseNotify();
  virtual ~DataBaseNotify();

  DataBaseNotify(const DataBaseNotify& from);
  DataBaseNotify(DataBaseNotify&& from) noexcept
    : DataBaseNotify() {
    *this = ::std::move(from);
  }

  inline DataBaseNotify& operator=(const DataBaseNotify& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataBaseNotify& operator=(DataBaseNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataBaseNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataBaseNotify* internal_default_instance() {
    return reinterpret_cast<const DataBaseNotify*>(
               &_DataBaseNotify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DataBaseNotify& a, DataBaseNotify& b) {
    a.Swap(&b);
  }
  inline void Swap(DataBaseNotify* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataBaseNotify* New() const final {
    return CreateMaybeMessage<DataBaseNotify>(nullptr);
  }

  DataBaseNotify* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataBaseNotify>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataBaseNotify& from);
  void MergeFrom(const DataBaseNotify& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataBaseNotify* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DataBaseNotify";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ServerLink_2eproto);
    return ::descriptor_table_ServerLink_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDbIpFieldNumber = 1,
    kDbPortFieldNumber = 2,
  };
  // string db_ip = 1;
  void clear_db_ip();
  const std::string& db_ip() const;
  void set_db_ip(const std::string& value);
  void set_db_ip(std::string&& value);
  void set_db_ip(const char* value);
  void set_db_ip(const char* value, size_t size);
  std::string* mutable_db_ip();
  std::string* release_db_ip();
  void set_allocated_db_ip(std::string* db_ip);

  // uint32 db_port = 2;
  void clear_db_port();
  ::PROTOBUF_NAMESPACE_ID::uint32 db_port() const;
  void set_db_port(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:DataBaseNotify)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr db_ip_;
  ::PROTOBUF_NAMESPACE_ID::uint32 db_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ServerLink_2eproto;
};
// -------------------------------------------------------------------

class ServerMessageRegister :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerMessageRegister) */ {
 public:
  ServerMessageRegister();
  virtual ~ServerMessageRegister();

  ServerMessageRegister(const ServerMessageRegister& from);
  ServerMessageRegister(ServerMessageRegister&& from) noexcept
    : ServerMessageRegister() {
    *this = ::std::move(from);
  }

  inline ServerMessageRegister& operator=(const ServerMessageRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerMessageRegister& operator=(ServerMessageRegister&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerMessageRegister& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerMessageRegister* internal_default_instance() {
    return reinterpret_cast<const ServerMessageRegister*>(
               &_ServerMessageRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ServerMessageRegister& a, ServerMessageRegister& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerMessageRegister* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerMessageRegister* New() const final {
    return CreateMaybeMessage<ServerMessageRegister>(nullptr);
  }

  ServerMessageRegister* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerMessageRegister>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerMessageRegister& from);
  void MergeFrom(const ServerMessageRegister& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerMessageRegister* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerMessageRegister";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ServerLink_2eproto);
    return ::descriptor_table_ServerLink_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageStrFieldNumber = 1,
  };
  // repeated string message_str = 1;
  int message_str_size() const;
  void clear_message_str();
  const std::string& message_str(int index) const;
  std::string* mutable_message_str(int index);
  void set_message_str(int index, const std::string& value);
  void set_message_str(int index, std::string&& value);
  void set_message_str(int index, const char* value);
  void set_message_str(int index, const char* value, size_t size);
  std::string* add_message_str();
  void add_message_str(const std::string& value);
  void add_message_str(std::string&& value);
  void add_message_str(const char* value);
  void add_message_str(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& message_str() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_message_str();

  // @@protoc_insertion_point(class_scope:ServerMessageRegister)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> message_str_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ServerLink_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerLink

// string server_str = 1;
inline void ServerLink::clear_server_str() {
  server_str_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ServerLink::server_str() const {
  // @@protoc_insertion_point(field_get:ServerLink.server_str)
  return server_str_.GetNoArena();
}
inline void ServerLink::set_server_str(const std::string& value) {
  
  server_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerLink.server_str)
}
inline void ServerLink::set_server_str(std::string&& value) {
  
  server_str_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerLink.server_str)
}
inline void ServerLink::set_server_str(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  server_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerLink.server_str)
}
inline void ServerLink::set_server_str(const char* value, size_t size) {
  
  server_str_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerLink.server_str)
}
inline std::string* ServerLink::mutable_server_str() {
  
  // @@protoc_insertion_point(field_mutable:ServerLink.server_str)
  return server_str_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ServerLink::release_server_str() {
  // @@protoc_insertion_point(field_release:ServerLink.server_str)
  
  return server_str_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ServerLink::set_allocated_server_str(std::string* server_str) {
  if (server_str != nullptr) {
    
  } else {
    
  }
  server_str_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), server_str);
  // @@protoc_insertion_point(field_set_allocated:ServerLink.server_str)
}

// -------------------------------------------------------------------

// DataBaseNotify

// string db_ip = 1;
inline void DataBaseNotify::clear_db_ip() {
  db_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DataBaseNotify::db_ip() const {
  // @@protoc_insertion_point(field_get:DataBaseNotify.db_ip)
  return db_ip_.GetNoArena();
}
inline void DataBaseNotify::set_db_ip(const std::string& value) {
  
  db_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DataBaseNotify.db_ip)
}
inline void DataBaseNotify::set_db_ip(std::string&& value) {
  
  db_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DataBaseNotify.db_ip)
}
inline void DataBaseNotify::set_db_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  db_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DataBaseNotify.db_ip)
}
inline void DataBaseNotify::set_db_ip(const char* value, size_t size) {
  
  db_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DataBaseNotify.db_ip)
}
inline std::string* DataBaseNotify::mutable_db_ip() {
  
  // @@protoc_insertion_point(field_mutable:DataBaseNotify.db_ip)
  return db_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DataBaseNotify::release_db_ip() {
  // @@protoc_insertion_point(field_release:DataBaseNotify.db_ip)
  
  return db_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DataBaseNotify::set_allocated_db_ip(std::string* db_ip) {
  if (db_ip != nullptr) {
    
  } else {
    
  }
  db_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), db_ip);
  // @@protoc_insertion_point(field_set_allocated:DataBaseNotify.db_ip)
}

// uint32 db_port = 2;
inline void DataBaseNotify::clear_db_port() {
  db_port_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DataBaseNotify::db_port() const {
  // @@protoc_insertion_point(field_get:DataBaseNotify.db_port)
  return db_port_;
}
inline void DataBaseNotify::set_db_port(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  db_port_ = value;
  // @@protoc_insertion_point(field_set:DataBaseNotify.db_port)
}

// -------------------------------------------------------------------

// ServerMessageRegister

// repeated string message_str = 1;
inline int ServerMessageRegister::message_str_size() const {
  return message_str_.size();
}
inline void ServerMessageRegister::clear_message_str() {
  message_str_.Clear();
}
inline const std::string& ServerMessageRegister::message_str(int index) const {
  // @@protoc_insertion_point(field_get:ServerMessageRegister.message_str)
  return message_str_.Get(index);
}
inline std::string* ServerMessageRegister::mutable_message_str(int index) {
  // @@protoc_insertion_point(field_mutable:ServerMessageRegister.message_str)
  return message_str_.Mutable(index);
}
inline void ServerMessageRegister::set_message_str(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ServerMessageRegister.message_str)
  message_str_.Mutable(index)->assign(value);
}
inline void ServerMessageRegister::set_message_str(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ServerMessageRegister.message_str)
  message_str_.Mutable(index)->assign(std::move(value));
}
inline void ServerMessageRegister::set_message_str(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  message_str_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ServerMessageRegister.message_str)
}
inline void ServerMessageRegister::set_message_str(int index, const char* value, size_t size) {
  message_str_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ServerMessageRegister.message_str)
}
inline std::string* ServerMessageRegister::add_message_str() {
  // @@protoc_insertion_point(field_add_mutable:ServerMessageRegister.message_str)
  return message_str_.Add();
}
inline void ServerMessageRegister::add_message_str(const std::string& value) {
  message_str_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ServerMessageRegister.message_str)
}
inline void ServerMessageRegister::add_message_str(std::string&& value) {
  message_str_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ServerMessageRegister.message_str)
}
inline void ServerMessageRegister::add_message_str(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  message_str_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ServerMessageRegister.message_str)
}
inline void ServerMessageRegister::add_message_str(const char* value, size_t size) {
  message_str_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ServerMessageRegister.message_str)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ServerMessageRegister::message_str() const {
  // @@protoc_insertion_point(field_list:ServerMessageRegister.message_str)
  return message_str_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ServerMessageRegister::mutable_message_str() {
  // @@protoc_insertion_point(field_mutable_list:ServerMessageRegister.message_str)
  return &message_str_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ServerLink_2eproto
